import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * The sidebar is generated from the `docs/` folder tree. Category labels/order come from each
 * folder's `_category_.json`; page order from `sidebar_position` in each page's frontmatter.
 */
const sidebars: SidebarsConfig = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
